site_name: 研究メモ

theme:
  name: material
  features:
    - navigation.instant
  language: ja
  palette:
    scheme: slate
    primary: indigo

plugins:
  - search:
      lang: ja
  - awesome-nav
  - pagetree


extra:
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
