site_name: 研究メモ
site_url: https://research-notes.nagutabby.uk
site_description: これまでに読んだ論文や活動報告のための週報を掲載しています。

theme:
  name: material
  features:
    - navigation.instant
  language: ja
  palette:
    scheme: slate
    primary: indigo
  font:
    text: Noto Sans JP

plugins:
  - search:
      lang: ja
  - awesome-nav
  - pagetree
  - meta
  - git-revision-date-localized
  - social:
      cards_layout_options:
        font_family: Noto Sans JP

extra:
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

draft_docs: |
  research-papers/templates/
  weekly-reports/templates/
